### ISSUE TITLE
Does not work in Ubuntu 22.04 with AttributeError: type object 'ApplicationFlags' has no attribute 'DEFAULT_FLAGS'

### ISSUE THREAD

**Issue by archisman-panigrahi** [slgobinath/SafeEyes#623]
**Describe the bug**
Safe Eyes fails to open in Ubuntu 22.04 which has python 3.10.

**Desktop (please complete the following information):**
 - OS: 22.04
 - Desktop Env: XFCE
 - Version: latest master branch https://github.com/slgobinath/SafeEyes/commit/cddee2a468ad60e54bcbf2042da11c8e0e85a91f

**Debug Log**

```
~$ safeeyes --debug
2024-08-05 22:14:06,260 [DEBUG]:[MainThread] Initialize the platform
2024-08-05 22:14:06,286 [INFO]:[MainThread] Starting Safe Eyes
Traceback (most recent call last):
  File "/usr/bin/safeeyes", line 33, in <module>
    sys.exit(load_entry_point('safeeyes==2.2.1', 'console_scripts', 'safeeyes')())
  File "/usr/lib/python3/dist-packages/safeeyes/__main__.py", line 130, in main
    safe_eyes = SafeEyes(system_locale, config, args)
  File "/usr/lib/python3/dist-packages/safeeyes/safeeyes.py", line 55, in __init__
    flags=Gio.ApplicationFlags.DEFAULT_FLAGS
AttributeError: type object 'ApplicationFlags' has no attribute 'DEFAULT_FLAGS'
```

Works without any issue in ubuntu 24.04 (python3.12).

**Comment by archisman-panigrahi** [comment]
@deltragon Can we let it pass if there is an attribute error?

**Comment by deltragon** [comment]
Oh, interesting.
According to [this](https://lazka.github.io/pgi-docs/index.html#Gio-2.0/flags.html#Gio.ApplicationFlags.FLAGS_NONE), DEFAULT_FLAGS is the same as FLAGS_NONE, and was introduced in Gio 2.74 (and at the same time FLAGS_NONE was marked as deprecated) - but Ubuntu 22.04 still has [1.72](https://packages.ubuntu.com/jammy/gobject-introspection) in its repos.
I wasn't aware this change/depreciation was this recent - i think the best thing is to simply switch back to FLAGS_NONE for now, as that also means it probably won't be removed for quite a while.

**Comment by archisman-panigrahi** [comment]
Thanks! It worked!

**Comment by archisman-panigrahi** [comment]
> Gio 2.74

It is probably 1.74

**Comment by archisman-panigrahi** [comment]
Also verified that it works with latest Arch. Though deprecated, it still works.

**Comment by archisman-panigrahi** [comment]
I am going to release a new version soon, since it has updated translation and a few more bug fixes.
