### ISSUE TITLE
Plugins not working with python 3.11

### ISSUE THREAD

**Issue by mcschempp** [slgobinath/SafeEyes#524]
**Describe the bug**
When using python 3.11, I get the following exception for all plugins:

```
Traceback (most recent call last):
  File "/usr/lib/python3.11/site-packages/safeeyes/plugin_manager.py", line 86, in init
    self.__load_plugin(plugin)
  File "/usr/lib/python3.11/site-packages/safeeyes/plugin_manager.py", line 303, in __load_plugin
    self.__init_plugin(module, plugin_obj)
  File "/usr/lib/python3.11/site-packages/safeeyes/plugin_manager.py", line 324, in __init_plugin
    if utility.has_method(module, 'on_start'):
       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/safeeyes/utility.py", line 669, in has_method
    if len(inspect.getargspec(getattr(module, method_name)).args) == no_of_args:
           ^^^^^^^^^^^^^^^^^^
AttributeError: module 'inspect' has no attribute 'getargspec'
```
[safeeyes.log](https://github.com/slgobinath/SafeEyes/files/11428642/safeeyes.log)

might be related to https://github.com/pyinvoke/invoke/issues/833

**To Reproduce**
1. open `safeeyes/plugin_manager.py` in an editor
2. log the BaseException in line 87 with `logging.exception`

**Expected behavior**
the exception should not happe

**Desktop (please complete the following information):**
 - OS: Arch Linux
 - Desktop Env: i3
 - Version:  2.1.5

**Comment by mcschempp** [comment]
I fixed this issue by applying the suggested workaround mentioned in https://github.com/pyinvoke/invoke/issues/833#issuecomment-1293148106

I opened `/usr/lib/python3.11/site-packages/safeeyes/utility.py`  and added

```python
if not hasattr(inspect, 'getargspec'):
    inspect.getargspec = inspect.getfullargspec
```

after

```python
import inspect
```

**Comment by BrunoBernardino** [comment]
I just had the same issue (Manjaro, so Arch-based), and the workaround fixed it, thanks!

**Comment by hartwork** [comment]
This seems to be a duplicate of #491 and #522 which are both fixed by #505 on Git `master`.

**Comment by hartwork** [comment]
@slgobinath can this be closed as fixed in 2.1.6?

**Comment by slgobinath** [comment]
Yes it can be closed.
Thanks @hartwork
